version: '3.7'

services:
  xml-to-turtle:
    build: .
    container_name: xml-to-turtle
    image: libapps-admin.uncw.edu:8000/randall-dev/digitalmeasures-scripts/xml-to-turtle
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./app:/app
      - ./output:/output
    restart: always
