version: '3.7'

services:
  vivo-data-update:
    build: .
    container_name: vivo-data-update
    image: libapps-admin.uncw.edu:8000/randall-dev/vivo-data-update
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./app:/app
      - ./output:/output
    restart: always
